# Generated by Django 4.2.28 on 2026-04-03 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libaries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowdocument',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowdocument',
            name='status',
            field=models.CharField(choices=[('BORROWING', 'Borrowing'), ('RETURNED', 'Returned'), ('OVERDUE', 'Overdue')], default='BORROWING', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together={('user', 'document')},
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'document')},
        ),
        migrations.CreateModel(
            name='DocumentView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libaries.document')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
