# Generated by Django 6.0.4 on 2026-04-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libaries', '0003_alter_borrowdocument_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='borrowdocument',
            unique_together={('user', 'document', 'borrow_date')},
        ),
    ]
