# Generated by Django 6.0.4 on 2026-04-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libaries', '0004_alter_borrowdocument_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='is_paid',
            new_name='is_free',
        ),
    ]
