# Generated by Django 6.0.4 on 2026-04-29 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libaries', '0005_rename_is_paid_document_is_free'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
    ]
