# Generated by Django 6.0.4 on 2026-05-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libaries', '0006_alter_payment_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('PAYPAL', 'Paypal'), ('STRIPE', 'Stripe')], max_length=20),
        ),
    ]
