# Generated by Django 6.0.4 on 2026-05-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libaries', '0007_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[('ADMIN', 'Admin'), ('READER', 'Reader'), ('LIBRARIAN', 'Librarian')], default='READER'),
        ),
    ]
