"""
Django settings for smartlib project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ihob_+-i_&!j+6yz%_nm75a0r2882^*rm0%828!yg$r$945y*i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'libaries.apps.LibariesConfig',
    # 'ckeditor',
    # 'ckeditor_uploader',
    'rest_framework',
    'drf_yasg',
    'oauth2_provider'

]

ALLOWED_HOSTS=['192.168.1.7', '127.0.0.1']

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',

    )
}

OAUTH2_PROVIDER = {
    'ACCESS_TOKEN_EXPIRE_SECONDS': 3600
}

import cloudinary.api

cloudinary.config(
    cloud_name="dut04a4ht",
    api_key="132394211371326",
    api_secret="F4SN3ot9LMrGYnG88yxulbq7XHM"
)

ROOT_URLCONF = 'smartlib.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartlib.wsgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


AUTH_USER_MODEL = "libaries.User"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'libary_db',
        'USER': 'root',
        'PASSWORD': 'abc123',
        'HOST': ''  # mặc định localhost
    }
}

import pymysql
pymysql.version_info = (2, 2, 2, "final", 0)
pymysql.install_as_MySQLdb()

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

CLIENT_ID = "9q2ApGFsFHBaGucEFVUT5PU61WvCKzbIcwDBe92I"
CLIENT_SECRET = "p8BDS8cumv5lMN2n2gAUTz7nXqWipJgCdoleOwdP6C9xDja7WlI7CXlMO0PZqKHjFRmYIR1muTJAlA1YiGntiKPM9pWaeQhLCWk13JZaJ7sxW8nEPdYPSYX1GbPn1hZY"

STRIPE_PUBLIC_KEY = "pk_test_51TR4f8DvmupqnhvtiC5u53SwJwUfAIcVq3fuDvlIEYYrnc8bJjC8YikHbXfSaoArYz53Ojn3COFp6r0qOMvO63ts008lQdyfvU"
STRIPE_SECRET_KEY = "sk_test_51TR4f8Dvmupqnhvtub8g63k8a8C5GfIftf6WuoXKpdALXLL0frF8q3edm1xiKIAaYvSzWPwO3n7ZKPWhOWi5Fy0u008NDNudVV"
STRIPE_WEBHOOK_SECRET="whsec_cMO5n9AOt6oQUOHUebCGUps3GmiHquca"

PAYMENT_SUCCESS_URL="http://localhost:3000/payment-success/"
PAYMENT_CANCEL_URL="http://localhost:3000/payment-cancel/"
